#cloud-config
hostname: debug
timezone: America/New_York
users:
  - default
  - name: nodadyoushutup
    groups:
      - sudo
    shell: /bin/bash
    plain_text_passwd: "${password}"
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
package_update: true
packages:
  - qemu-guest-agent
  - net-tools
  - curl
runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - echo "done" > /tmp/cloud-config.done